// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface AppointmentOption {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subtitle?: string;
  url?: string;
  icon?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Clinician {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  role: string;
  credentials?: string;
  bio?: string;
  initials?: string;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Clinic {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  address1?: string;
  address2?: string;
  town?: string;
  postcode?: string;
  image?: string;
  link?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer: string;
  category: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HomeSection {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subtitle?: string;
  description?: string;
  content?: string;
  button_text?: string;
  button_url?: string;
  image?: string;
  secondary_image?: string;
  video_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Homepage {
  id: string;
  slug: string | null;
  status: string;
  hero_title: string;
  hero_subtitle?: string;
  hero_description?: string;
  hero_button_text?: string;
  hero_button_url?: string;
  hero_video_url?: string;
  founders_title?: string;
  founders_subtitle?: string;
  founders_description?: string;
  founders_content?: string;
  founders_button_text?: string;
  founders_button_url?: string;
  founders_image?: string;
  founders_secondary_image?: string;
  services_title?: string;
  services_subtitle?: string;
  services_description?: string;
  clinics_title?: string;
  clinics_subtitle?: string;
  clinics_description?: string;
  appointments_title?: string;
  appointments_subtitle?: string;
  appointments_description?: string;
  advice_title?: string;
  advice_subtitle?: string;
  advice_description?: string;
  clinicians_title?: string;
  clinicians_subtitle?: string;
  clinicians_description?: string;
  service1_title?: string;
  service1_price?: string;
  service1_text?: string;
  service1_link?: string;
  service1_image?: string;
  service2_title?: string;
  service2_price?: string;
  service2_text?: string;
  service2_link?: string;
  service2_image?: string;
  service3_title?: string;
  service3_price?: string;
  service3_text?: string;
  service3_link?: string;
  service3_image?: string;
  service4_title?: string;
  service4_price?: string;
  service4_text?: string;
  service4_link?: string;
  service4_image?: string;
  service5_title?: string;
  service5_price?: string;
  service5_text?: string;
  service5_link?: string;
  service5_image?: string;
  service6_title?: string;
  service6_price?: string;
  service6_text?: string;
  service6_link?: string;
  service6_image?: string;
  service7_title?: string;
  service7_price?: string;
  service7_text?: string;
  service7_link?: string;
  service7_image?: string;
  service8_title?: string;
  service8_price?: string;
  service8_text?: string;
  service8_link?: string;
  service8_image?: string;
  service9_title?: string;
  service9_price?: string;
  service9_text?: string;
  service9_link?: string;
  service9_image?: string;
  clinic1_title?: string;
  clinic1_address1?: string;
  clinic1_address2?: string;
  clinic1_town?: string;
  clinic1_postcode?: string;
  clinic1_image?: string;
  clinic1_link?: string;
  clinic2_title?: string;
  clinic2_address1?: string;
  clinic2_address2?: string;
  clinic2_town?: string;
  clinic2_postcode?: string;
  clinic2_image?: string;
  clinic2_link?: string;
  clinic3_title?: string;
  clinic3_address1?: string;
  clinic3_address2?: string;
  clinic3_town?: string;
  clinic3_postcode?: string;
  clinic3_image?: string;
  clinic3_link?: string;
  clinic4_title?: string;
  clinic4_address1?: string;
  clinic4_address2?: string;
  clinic4_town?: string;
  clinic4_postcode?: string;
  clinic4_image?: string;
  clinic4_link?: string;
  clinic5_title?: string;
  clinic5_address1?: string;
  clinic5_address2?: string;
  clinic5_town?: string;
  clinic5_postcode?: string;
  clinic5_image?: string;
  clinic5_link?: string;
  clinic6_title?: string;
  clinic6_address1?: string;
  clinic6_address2?: string;
  clinic6_town?: string;
  clinic6_postcode?: string;
  clinic6_image?: string;
  clinic6_link?: string;
  appointment1_title?: string;
  appointment1_subtitle?: string;
  appointment1_url?: string;
  appointment1_icon?: string;
  appointment2_title?: string;
  appointment2_subtitle?: string;
  appointment2_url?: string;
  appointment2_icon?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  hero_subtitle?: string;
  hero_title?: string;
  hero_description?: string;
  clinicians_title?: string;
  clinicians_description?: string;
  advice_title?: string;
  advice_description?: string;
  founders_subtitle?: string;
  founders_title?: string;
  founders_quote?: string;
  founders_body?: string;
  founders_button_text?: string;
  founders_button_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  price?: string;
  text?: string;
  link?: string;
  image?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    appointments: AppointmentOption;
    clinicians: Clinician;
    clinics: Clinic;
    faqs: Faq;
    home_sections: HomeSection;
    homepage: Homepage;
    pages: Page;
    posts: Post;
    services: Service;
  }
}