// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface AppointmentOption {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subtitle?: string;
  url?: string;
  icon?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Clinician {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  role: string;
  credentials?: string;
  bio?: string;
  initials?: string;
  featured?: boolean;
  image?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Clinic {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  address1?: string;
  address2?: string;
  town?: string;
  postcode?: string;
  image?: string;
  link?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer: string;
  category: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Section {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subtitle?: string;
  description?: string;
  content?: string;
  button_text?: string;
  button_url?: string;
  image?: string;
  secondary_image?: string;
  video_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  price?: string;
  text?: string;
  link?: string;
  image?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    appointments: AppointmentOption;
    clinicians: Clinician;
    clinics: Clinic;
    faqs: Faq;
    home_sections: Section;
    pages: Page;
    posts: Post;
    services: Service;
  }
}